@startuml
title 第三方送检主流程
== 发起送检单 ==
同舟系统 -> 品控工作台: 填写预约送检单申请信息，调用品控提供的RPC接口，生成送检单\n参数: 送检类型、商品id、供应商id、样品数量、样品类型、送检机构\n付费方、送检方联系人、送检方联系邮箱、送检方联系电话

品控工作台-> 品控工作台: 生成送检单id，送检单基础信息落库，itext生成送检单说明单pdf
品控工作台-> 工单系统: 调用工单RPC接口生成送检工单
工单系统-> 品控工作台: 生成的工单id
品控工作台->品控工作台: 更新送检单基础信息表TB_YX_QC_INSPECTION_SHEET_INFO，更新对应的工单id
品控工作台 -> 同舟系统: 返回生成的送检单id

同舟系统->品控工作台:填写送检物流信息，调用品控rpc接口更新送检单物流信息\n参数:送检单id，物流公司编号、物流单号、送达时间
品控工作台->品控工作台:物流信息落库 表TB_YX_QC_INSPECTION_DELIVERY_INFO
品控工作台->工单系统:调用工单系统的rpc接口更新对应送检工单的物流信息
note left:物流轨迹使用严选物流中间件查询



== 制定送检标准指标 ==
品控工作台 -> ApolloY: 获取商品对应SQE判断指派人规则
ApolloY -> 品控工作台: 返回配置
品控工作台->工单系统: 指定工单接收人，调用工单RPC接口更新工单数据
alt 引用神匠模块化指标
    品控工作台->品控神匠: 调用神匠http接口，获取神匠指标列表
品控神匠->品控工作台:返回指标列表
else 上传指标附件
    品控工作台-> FMS: 上传指标附件到fms
end

品控工作台-> 工单系统: 更新对应工单的指标信息

品控工作台->供应商协同系统:获取送检单指定的第三方送检机构信息\n参数：送检机构对应的id
供应商协同系统-> 品控工作台: 返回送检机构信息
品控工作台->UAS: 发送邮件、短信通知第三方送检机构
 
== 送检机构确认送检指标 ==
    同舟系统->品控工作台: 调用品控工作台审核送检指标rpc接口\n参数: 送检工单id、送检结果、通过or驳回原因（驳回时必填）
    alt 送检机构确认指标可行
        品控工作台->工单系统:调用工单rpc接口跳转到送检机构填写送检结果节点
    else 送检机构驳回
        品控工作台-> 工单系统:调用工单rpc接口跳回到严选确认送检指标
    end

== 送检机构填写送检结果 ==
同舟系统->品控工作台: 调用品控rpc接口发送送检整体结果\n参数:送检工单id，送检结果（通过，不通过，不适用）、送检结果单附件、送检不合格项、\n送检不合格次数、中间过程不通过检测结果附件、补加指标、补加指标原因、送检费用
品控工作台->工单系统: 将送检结果更新到对应的送检工单

== 严选确认送检结果 ==
品控工作台->工单系统: 更新确认结果到工单，支持编辑付费方
alt 确认送检结果
    品控工作台->品控工作台: 落库送检单结果信息TB_YX_QC_INSPECTION_SHEET_RESULT、\n送检不合格项TB_YX_QC_INSPECTION_UNQUALIFIED_DETAIL\n更新送检单状态TB_YX_QC_INSPECTION_SHEET_INFO

else 严选驳回送检结果
    品控工作台->工单系统: 送检工单跳回送检机构填写送检结果节点

end


@enduml